### ISSUE TITLE
Update ExtractFingerprint Type to use GitProject

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm-pack-fingerprint#149]
Currently, `p` is defined as `Project` however at runtime the `p` object has a `baseDir` property and I believe it should be`GitProject`.   

https://github.com/atomist/sdm-pack-fingerprint/blob/master/lib/machine/Aspect.ts#L85

**Comment by cdupuis** [comment]
Probably `LocalProject` instead of `GitProject`.
