### ISSUE TITLE
Remove hardcode Github references

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm-pack-fingerprint#51]
Currently, if you use this pack with a VCS that is not Github the links are incorrect

https://github.com/atomist/sdm-pack-fingerprints/blob/afec3929e8db30b34f7adf7fb5c2f8f0c85869b4/lib/handlers/commands/applyFingerprint.ts#L72

https://github.com/atomist/sdm-pack-fingerprints/blob/afec3929e8db30b34f7adf7fb5c2f8f0c85869b4/lib/handlers/commands/applyFingerprint.ts#L102

**Comment by slimslenderslacks** [comment]
fix is in 3.0 version of the pack - this is the version where we move to custom ingestion and storing targets in the new TeamConfiguration model.
